# Generated by Django 3.2.8 on 2021-10-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KenParamMT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ken_name', models.CharField(max_length=5)),
                ('ken_no', models.IntegerField()),
                ('ken_block_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MdUrlMT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md_url', models.CharField(max_length=200)),
            ],
        ),
    ]
