# Generated by Django 3.2.8 on 2021-12-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapingSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobparamdetaildata',
            name='job_ken',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='jobparamdetaildata',
            name='job_md_item',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='processresultdetaildata',
            name='target_ken',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='processresultdetaildata',
            name='target_md_item',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
