# Generated by Django 3.2.8 on 2021-10-30 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapingSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MDItemMT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md_item', models.CharField(max_length=10)),
            ],
        ),
    ]
