# Generated by Django 3.2.8 on 2021-11-05 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapingSystem', '0002_mditemmt'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('mail_address', models.CharField(max_length=50)),
                ('pass_word', models.CharField(max_length=10)),
            ],
        ),
    ]
