# Generated by Django 3.2.8 on 2021-11-05 13:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scrapingSystem', '0003_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileManageData',
            fields=[
                ('result_file_num', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('create_file', models.FileField(upload_to='file/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralCodeMT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_group_key', models.CharField(max_length=8)),
                ('general_key', models.CharField(max_length=8)),
                ('general_code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JobParamData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_num', models.IntegerField(max_length=20)),
                ('param_name', models.CharField(max_length=10)),
                ('param', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='JobQueData',
            fields=[
                ('job_num', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessResultData',
            fields=[
                ('result_file_num', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=10)),
                ('file_create_status', models.CharField(max_length=10)),
                ('create_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('target_start_year', models.CharField(max_length=5)),
                ('target_end_year', models.CharField(max_length=5)),
                ('target_start_month', models.CharField(max_length=3)),
                ('target_end_month', models.CharField(max_length=3)),
                ('target_ken', models.CharField(max_length=5)),
                ('target_md_item', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='SaibanMT',
            fields=[
                ('saiban_key', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('saiban_count', models.IntegerField()),
                ('saiban_ketasu', models.IntegerField(max_length=20)),
                ('saiban_init_num', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='userdata',
            name='mail_address',
            field=models.EmailField(max_length=254),
        ),
        migrations.AddConstraint(
            model_name='jobparamdata',
            constraint=models.UniqueConstraint(fields=('job_num', 'param_name'), name='unique_job'),
        ),
        migrations.AddConstraint(
            model_name='generalcodemt',
            constraint=models.UniqueConstraint(fields=('general_group_key', 'general_key'), name='unique_general_code'),
        ),
    ]
