# Generated by Django 3.2.8 on 2021-11-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapingSystem', '0004_auto_20211105_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobparamdata',
            name='job_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='jobquedata',
            name='job_num',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='saibanmt',
            name='saiban_ketasu',
            field=models.IntegerField(),
        ),
    ]
