# Generated by Django 3.2.8 on 2021-11-06 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapingSystem', '0005_auto_20211105_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobquedata',
            name='result_file_num',
            field=models.CharField(default=20211122121213333333, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filemanagedata',
            name='result_file_num',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jobparamdata',
            name='job_num',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='jobquedata',
            name='job_num',
            field=models.CharField(max_length=13, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='processresultdata',
            name='result_file_num',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
