# Generated by Django 3.2.8 on 2021-11-06 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapingSystem', '0006_auto_20211106_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobparamdata',
            name='param_name',
            field=models.CharField(max_length=20),
        ),
    ]
