# Generated by Django 3.2.8 on 2021-11-06 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapingSystem', '0007_alter_jobparamdata_param_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processresultdata',
            name='file_create_status',
            field=models.CharField(max_length=20),
        ),
    ]
