# Generated by Django 3.2.8 on 2021-11-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapingSystem', '0008_alter_processresultdata_file_create_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saibanmt',
            name='saiban_init_num',
            field=models.CharField(max_length=100),
        ),
    ]
