# Generated by Django 3.2.8 on 2021-11-06 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapingSystem', '0009_alter_saibanmt_saiban_init_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saibanmt',
            name='saiban_init_num',
        ),
    ]
