# Generated by Django 3.2.8 on 2021-11-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapingSystem', '0010_remove_saibanmt_saiban_init_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemanagedata',
            name='create_file',
            field=models.FileField(max_length=500, upload_to='file/%Y/%m/%d'),
        ),
    ]
