# Generated by Django 3.2.8 on 2021-11-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapingSystem', '0011_alter_filemanagedata_create_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemanagedata',
            name='user_id',
            field=models.CharField(default=21, max_length=10),
            preserve_default=False,
        ),
    ]
