# Generated by Django 3.2.8 on 2021-11-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapingSystem', '0012_filemanagedata_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemanagedata',
            name='create_file',
            field=models.FileField(max_length=500, upload_to='file'),
        ),
    ]
