# Generated by Django 3.2.8 on 2021-11-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapingSystem', '0013_alter_filemanagedata_create_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskManageMt',
            fields=[
                ('task_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('task_process_flag', models.CharField(max_length=1)),
            ],
        ),
    ]
